language: ruby
rvm:
 - 2.0.0
 - 2.3.0
services:
 - mysql
before_install:
  - mysql -e 'CREATE DATABASE workhorse;'
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
script:
 - bundle install
 - bundle exec rake test
 - bundle exec rubocop
